
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 01:05:10 CST 2018
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 35;
  public static final int PALCLAVMETODOS = 8;
  public static final int DOSPUNTOS = 30;
  public static final int PALCLAVINCLUIR = 6;
  public static final int PALCLAVPROPIEDADES = 7;
  public static final int MENSAJE = 36;
  public static final int PARENABRE = 26;
  public static final int OPMATEMATICO = 18;
  public static final int PALCLAVENTONCES = 13;
  public static final int ARCHIVOEXCEL = 21;
  public static final int PALCLAVCODIGO = 11;
  public static final int IDENTIFICADOR = 3;
  public static final int ESPBLANCO = 31;
  public static final int IGUAL = 20;
  public static final int PROPIEDADID = 19;
  public static final int CORCHABRE = 37;
  public static final int TIPODEDATO = 22;
  public static final int TAB = 24;
  public static final int ARCHIVOLED = 23;
  public static final int PALCLAVESCRIBIR = 16;
  public static final int PALCLAVABRIR = 17;
  public static final int PALCLAVFUNCION = 5;
  public static final int EOF = 0;
  public static final int PALCLAVPRINCIPAL = 4;
  public static final int COMILLAS = 28;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int TABS = 29;
  public static final int PALCLAVARCHIVOS = 9;
  public static final int PALCLAVSINO = 15;
  public static final int PCOMA = 32;
  public static final int PUNTO = 34;
  public static final int PALCLAVCLASE = 2;
  public static final int FINLINEA = 25;
  public static final int PALCLAVRETORNAR = 14;
  public static final int PALCLAVVARIABLES = 10;
  public static final int PARENCIERRA = 27;
  public static final int CORCHCIERRA = 38;
  public static final int PALCLAVSI = 12;
}

