
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 13 11:05:55 CST 2018
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int IDENTIFICADOR = 3;
  public static final int PALCLAVCLASE = 2;
  public static final int DOSPUNTOS = 4;
  public static final int ESPBLANCO = 5;
  public static final int EOF = 0;
}

